import "./globals.css";
import Providers from "@/components/Providers";
import MapContainer from "@/container/MapContainer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <MapContainer />
          {children}
        </Providers>
      </body>
    </html>
  );
}
