import "./globals.css";
import Providers from "@/components/Providers";
import Map from "@/components/common/Map";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Map />
          {children}
        </Providers>
      </body>
    </html>
  );
}
